language: ruby

matrix:
  include:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: 2.2.0
    - rvm: 2.3.0
    - rvm: rbx-2
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: jruby-1.7
      jdk: openjdk7
    - rvm: jruby-1.7
      jdk: oraclejdk7
    - rvm: jruby-1.7
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: openjdk7
    - rvm: jruby-head
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: oraclejdk8
    - rvm: jruby-9.0.4.0
      jdk: openjdk7
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk7
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk8
  allow_failures:
    - rvm: ruby-head
sudo: false
addons:
  apt:
    packages:
    - libpcre3
    - libpcre3-dev
before_install:
  - gem install bundler
before_script: export JRUBY_OPTS="--server -J-Xss1024k -J-Xmx652m -J-XX:+UseConcMarkSweepGC"

notifications:
#  irc: "irc.freenode.org#adhearsion"
#
  email:
    recipients:
      secure: Vkz6LJ7uvz4h4yOUBGzGBw759XfI7hlnZAl8tdXtklcT11+A38F0RaDmIKjcs8/msBUcvDvuVQdjobLxovTRmjetRIrys1IUXsXJWd//5ogmYIhOgIn5esYKXxLYAZS/m6PP8ekMZJeW/P3OCWBOTO8tjeUrYN9bAda8/KKzoKU=
