language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo apt-get install libpcre3 libpcre3-dev

notifications:
  irc: "irc.freenode.org#adhearsion"

  email:
    recipients:
      secure: Vkz6LJ7uvz4h4yOUBGzGBw759XfI7hlnZAl8tdXtklcT11+A38F0RaDmIKjcs8/msBUcvDvuVQdjobLxovTRmjetRIrys1IUXsXJWd//5ogmYIhOgIn5esYKXxLYAZS/m6PP8ekMZJeW/P3OCWBOTO8tjeUrYN9bAda8/KKzoKU=
