language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx-2.4
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo apt-get install libpcre3 libpcre3-dev

notifications:
  irc: "irc.freenode.org#adhearsion"
